### PR TITLE
Improvements to semantics and accessibility

### PR DESCRIPTION
**Pull request by caleb531**
This pull request proposes a series of changes intended to improve the readability of your site for search engines and screen readers alike. The commits speak for themselves, but here is an overview of my proposed changes:

- Created proper document outline for all pages and posts
  - `<h1>` is used for site name in site header
  - `<h2>` is used for page/post title
  - `<h3>` is used for subsequent page/post section headings
- Added semantic elements around or in place of generic `<div>` and `<span>` elements
  - Wrap site navigation `<ul>` in `<nav>`
  - Use `<header>` instead of `<div class="center">` for post title/date containers
  - Use `<time>` (with proper `datetime` attribute) for post dates everywhere
- Miscellaneous improvements
  - Added missing `alt` text to site gravatar ``
  - Replaced unsemantic gradient divider div (separating post header and post content) with a cleaner CSS border

For what it's worth, you can use the [WAVE Chrome extension](http://wave.webaim.org/extension/) to test the accessibility of your site.

Let me know what you think! :)
Caleb

### CODE REVIEW

**Comment by jacksonrayhamilton** [comment]
The links on the blog index can be "excessively wide:"

<p align="center">screenshot of wide lines under anchors</p>

The horizontal spacing between the site navigation, the page title, and the divider on the About and Contact pages has become uneven since the update:

<p align="center">screenshot of uneven horizontal spacing</p>

I liked how the "unsemantic gradient divider div" looked. Could we keep that as it was or as a styled `hr`?

I don't like how the posts "know about" the outside layout, and therefore use `h3` as a "base." The posts should be oblivious to their container, because it makes them more modular and easier to write. So I would probably leave them as is, and either install some "header demoter" plugin to do this automatically (I would _not_ write one; not worth it), or style post content as if it were two headers below.

**Comment by caleb531** [comment]
1. A valid concern; it has been fixed
2. Dang, I was hoping you wouldn't notice, albeit I'm not surprised. :P The original spacing you are noticing is 0.83em (which is Chrome's default margin-top/bottom for headings). I changed it to 0.8em to make it somewhat less arbitrary, but I have since reverted it to 0.83em (explicitly this time) since you seem to find the original styling preferable.
3. I have resurrected the gradient divider, but as an `:after` pseudo-element instead of an `<hr />`. My reasoning is that `<hr />` is meant to be used as a ["paragraph-level thematic break"](https://www.w3.org/TR/html-markup/hr.html), but this gradient divider seems to be purely aesthetic.
4. You are right mention this. HTML5 actually removed the accessibility prohibition on multiple <h1> headings, so long as they were not overused. Therefore, to maintain accessibility while still guaranteeing reasonable modularity for your posts, I have demoted page/post titles from `<h2>` to `<h1>`, which implies that your post sections headings can be `##` instead of `###`. Furthermore, because each post title is inextricably linked to its respective post, and because the post title will always be shown as a heading with the post, each section heading is intrinsically an `<h2>`. Therefore, formatting your post section headings as `##` will still guarantee modularity because the hierarchy is relative to the post (beginning with its title) and not to the parent site.

Thoughts?
Caleb

**Comment by jacksonrayhamilton** [comment]
Looks better now. I think your argument for `<h2>` is reasonable.

I tried out the site with WAVE and noticed some "contrast errors". Any ideas for fixing those?

**Comment by caleb531** [comment]
It seems most of those contrast errors are due to the orange text in your `<code>` elements against the light gray background. You can view each error individually via the *Contrast* tab in the WAVE sidebar.

screen shot 2016-08-17 at 7 54 55 pm

I suggest changing the `color` of your `<code>` elements to match the `color` of your `<pre>` elements. Your `<pre>` elements don't seem to trigger any contrast errors, so updating `<code>` to match should fix the errors, as well as improve your blog's overall stylistic consistency.

**Comment by jacksonrayhamilton** [comment]
Thanks for the explanation, fixed the colors in f4efa7e.

**Pull request merged**
